# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://syfnick.github.io
date_format: "ordinal"
title: ni氪
subtitle: "程序猿一枚"
description: "孙一凡的个人博客"
keywords: 孙一凡, Nick SUN, syfnick
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
source_code: https://github.com/syfnick/syfnick.github.io
side_bar_repo_limit: 2

# ---------------- #
#      Author      #
# ---------------- #
author: Nick SUN
organization: ASUS
organization_url: https://www.asus.com.cn
location: Shanghai, China
email: syfnick@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
    use_coderay: true
    syntax_highlighter: rouge
    coderay:
        coderay_line_numbers:  nil
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - coderay
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: syfnick
weibo_username: syfnick
zhihu_username: syfnick

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: duoshuo
duoshuo_username: syfnick
disqus_username: syfnick
# 在使用 disqus 的时候可点击显示多说评论框
lazy_load_duoshuo: true

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [C++, JavaScript, PHP, AngularJS, Laravel]
skill_windows_keywords: [Win32 SDK, WinJS, WinRT, UWP]
